
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logsvolume
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed
  