
apiVersion: v1
kind: PersistentVolume
metadata:
  name: runsvolume
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed
  