
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testsvolume
spec:
  capacity:
    storage: 1500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed
  