apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runs-pvc
  namespace: excellentia
spec:
  storageClassName: managed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi