scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8090','host.docker.internal:8080','host.docker.internal:8085']
    
 
