apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-dashboards-conf
  labels:
    name: grafana-server-dashboards-conf
  namespace: excellentia
data:
  dashboards.yml: |-
    apiVersion: 1
    providers:
        - name: dashboards
          type: file
          disableDeletion: true
          editable: true
          options:
              path: /etc/grafana/provisioning/dashboards
              foldersFromFilesStructure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-datasources-conf
  labels:
    name: grafana-server-datasources-conf
  namespace: excellentia
data:
  datasources.yml: |-
    apiVersion: 1

    datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-service:9090
          editable: false
          jsonData:
            httpMethod: POST
            exemplarTraceIdDestinations:
              - name: trace_id
                datasourceUid: tempo
        - name: Tempo
          type: tempo
          access: proxy
          orgId: 1
          url: http://tempo-service:3200
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
          apiVersion: 1
          uid: tempo
          jsonData:
              httpMethod: GET
              tracesToLogs:
                  datasourceUid: 'loki'
        - name: Loki
          type: loki
          uid: loki
          access: proxy
          orgId: 1
          url: http://loki-service:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
          apiVersion: 1
          jsonData:
              derivedFields:
                  -   datasourceUid: tempo
                      matcherRegex: \[.+,(.+?),
                      name: TraceID
                      url: $${__value.raw}