apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
  labels:
    app: judge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
        - name: judge
          image: ramizouari/excellentia-judge
          imagePullPolicy: Always
          env:
            - name: SQL_SERVER
              value: "excellentia-mssql-server"
            - name: SQL_PORT
              value: "1433"
            - name: CPP
              value: "g++"
            - name: CC
              value: "gcc"
            - name: JAVAC
              value: "javac"
            - name: JAVA
              value: "java"
            - name: PYTHON
              value: "python3"
            - name: DISK_MOUNT
              value: "/data/runs"
            - name: DISK_LOG
              value: "/data/logs"
            - name: DISK_TESTS
              value: "/data/tests"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: runsvolume
              mountPath: "/data/runs"
              readOnly: true
            - name: testsvolume
              mountPath: "/data/tests"
              readOnly: true
            - name: logsvolume
              mountPath: "/data/logs"
