apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
  namespace: excellentia
  labels:
    app: judge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
        - name: judge
          image: ramizouari/excellentia-judge
          imagePullPolicy: Always
          env:
            - name: "DISCOVERY_COMPILER_URL"
              value: "http://compiler-service.excellentia:80"
            - name: "DISCOVERY_RUNNER_URL"
              value: "http://runner-service.excellentia:80"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: runsvolume
              mountPath: "/data/runs"
              readOnly: true
            - name: testsvolume
              mountPath: "/data/tests"
              readOnly: true
            - name: logsvolume
              mountPath: "/data/logs"
      volumes:
      - name: runsvolume
        persistentVolumeClaim:
          claimName: runs-pvc  
      - name: testsvolume
        persistentVolumeClaim:
          claimName: tests-pvc
      - name: logsvolume
        persistentVolumeClaim:
          claimName: logs-pvc