apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge-ingress
  namespace: excellentia

spec:
  ingressClassName: nginx
  rules:
#  - host: discovery.app.front
  - http:
      paths:
      - backend:
          service:
            name: judge-service
            port:
              number: 80
        path: /
        pathType: Prefix