apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: excellentia
spec:
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app: loki
  sessionAffinity: None
  type: ClusterIP