apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiler
  namespace: excellentia
  labels:
    app: compiler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compiler
  template:
    metadata:
      labels:
        app: compiler
    spec:
      containers:
        - name: compiler
          image: ramizouari/excellentia-compiler
          imagePullPolicy: Always
          env:
            - name: SQL_SERVER
              value: "excellentia-mssql-server"
            - name: SQL_PORT
              value: "1433"
            - name: CPP
              value: "g++"
            - name: CC
              value: "gcc"
            - name: JAVAC
              value: "javac"
            - name: JAVA
              value: "java"
            - name: PYTHON
              value: "python3"
            - name: DISK_MOUNT
              value: "/data/runs"
            - name: DISK_LOG
              value: "/data/logs"
            - name: DISK_TESTS
              value: "/data/tests"
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: runsvolume
              mountPath: "/data/runs"
            - name: testsvolume
              mountPath: "/data/tests"
              readOnly: true
            - name: logsvolume
              mountPath: "/data/logs"
      volumes:
        - name: runsvolume
          persistentVolumeClaim:
            claimName: runs-pvc  
        - name: testsvolume
          persistentVolumeClaim:
            claimName: tests-pvc
        - name: logsvolume
          persistentVolumeClaim:
            claimName: logs-pvc