apiVersion: v1
kind: Service
metadata:
  name: compiler
  labels:
    app: compiler
spec:
  selector:
      app: compiler
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  type: ClusterIP