
spring:
    config:
    #    import: "optional:configserver"
        import: "deployment.yml"
    application:
        name: excellentia-judge

management:
    endpoints:
        web:
            exposure:
                include:
                    - health
                    - info
                    - prometheus
                    - metrics
                    - logfile
                    - configprops
                    - env
    endpoint:
        health:
            show-components: "always"
            show-details: "always"
            probes:
                enabled: true

otel:
    url:
        tracer: "http://localhost:9411"