spring:
  application:
    name: excellentia-judge
server:
  port : 8080

discovery:
  compiler:
    url: "${CHECKER_URL:http://localhost:8085}"
  runner:
    url: "${RUNNER_URL:http://localhost:8090}"