spring:
  application:
    name: excellentia-judge
server:
  port : 8080

discovery:
  compiler:
    url: "${COMPILER_URL:http://localhost:8085}"
  runner:
    url: "${RUNNER_URL:http://localhost:8090}"

disk:
  logs: "${DISK_LOGS:/home/ramizouari/Academic/Excellentia/logs}"

logging:
  level:
    root: DEBUG
  file:
    name: "${disk.logs}/${spring.application.name}.log"
