compilers:
  java:
    command: "${JAVAC:/usr/bin/javac}"
    arguments: "-d {output} {input}"
  cpp:
    command: "${CPP:/usr/bin/g++}"
    flags: "-std=c++20"
    arguments: "-o {output} {input}"
  c:
    command: "${CC:/usr/bin/gcc}"
    flags: "-std=c17"
    arguments: "-o {output} {input}"

interpreters:
  system:
    command: "{input}"
    arguments: ""
  python:
    command: "${PYTHON:/usr/bin/python3}"
    arguments: "{input}"


disk:
    # Path: src/main/resources/application.yml
    # The path to the directory where the files will be stored
  runs: "${DISK_RUNS:/home/ramizouari/Academic/Excellentia/runs}"
  tests: "${DISK_TESTS:/home/ramizouari/Academic/Excellentia/tests}"
  logs: "${DISK_LOGS:/home/ramizouari/Academic/Excellentia/logs}"


# For now, change to host=excellentia-sql-server if excellentia-mssql-server is down
database:
  server: "${SQL_SERVER:excellentia-mssql-server}"
  host: "${database.server}.database.windows.net"
  port: "${SQL_PORT:1433}"
  database: "excellentia"
  user: "excellentia@${database.server}"
  password: "gl5@12345678"


spring:
  datasource:
    url: "jdbc:sqlserver://${database.host}:${database.port};database=${database.database};user=${database.user};password=${database.password};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: "create-drop"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: "8KB"
      max-file-size: "2MB"
      max-request-size: "3MB"
  config:
    #    import: "optional:configserver"
    import: "deployment.yml"
  cloud:
    config:
      enabled: false

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: "${OTEL_URL:http://collector:4317}"



#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
file:
  upload:
    #location: "${DISK_MOUNT:/home/ramizouari/Academic/Excellentia/mount}"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
          - logfile
          - configprops
          - env
  endpoint:
    health:
      show-components: "always"
      show-details: "always"
      probes:
        enabled: true

#logging:
#  level:
#    root: DEBUG
#
#
#    org:
#      springframework:
#        boot:
#          autoconfigure:
#            logging: DEBUG
#endpoints:
#  logfile:
#    sensitive: false
###Add a spring.config.import=configserver: property to your configuration.
#	If configuration is not required add spring.config.import=optional:configserver: instead.
#	To disable this check, set spring.cloud.config.enabled=false or
#	spring.cloud.config.import-check.enabled=false.
logging:
  file:
    name: "${disk.logs}/${spring.application.name}.log"
