apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: excellentia
  labels:
    app: runner
spec:
  replicas: 4
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: ramizouari/excellentia-runner
          imagePullPolicy: Always
          env:
            - name: SQL_SERVER
              value: "excellentia-mssql-server"
            - name: SQL_PORT
              value: "1433"
            - name: CPP
              value: "g++"
            - name: CC
              value: "gcc"
            - name: JAVAC
              value: "javac"
            - name: JAVA
              value: "java"
            - name: PYTHON
              value: "python3"
            - name: DISK_RUNS
              value: "/data/runs"
            - name: DISK_LOG
              value: "/data/logs"
            - name: DISK_TESTS
              value: "/data/tests"
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: runsvolume
              mountPath: "/data/runs"
              readOnly: true
            - name: testsvolume
              mountPath: "/data/tests"
              readOnly: true
            - name: logsvolume
              mountPath: "/data/logs"
      volumes:
      - name: runsvolume
        persistentVolumeClaim:
          claimName: runs-pvc  
      - name: testsvolume
        persistentVolumeClaim:
          claimName: tests-pvc
      - name: logsvolume
        persistentVolumeClaim:
          claimName: logs-pvc
            
