apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: excellentia
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus-server
  sessionAffinity: None
  type: LoadBalancer